org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap_crystalix
addon_name=BlueMap Crystalix Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-crystalix-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=47389
accepted_jar_sha256=512e02fda272a1c6809fb6c30ee3958cdf13fb87e531b23355069f177458721b
